# Generated by Django 3.2.3 on 2021-06-04 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='time_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
