# Generated by Django 3.2.3 on 2021-06-04 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0007_alter_following_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzer',
            name='following',
            field=models.ManyToManyField(related_name='follow_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
